[project]
name = "face-detector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "imutils>=0.5.4",
    "numpy>=2.3.5",
    "opencv-python>=4.11.0.86",
]
